### PR TITLE
Add picking support

### PR DESCRIPTION
**Pull request by jourdain**
## About

Adding picking capabilities
Adding CubeAxes on GeometryRepresentation

## Pre-Merge checklist
- [x] The project was correctly built with `npm run build`.
- [x] If there was any conflict, it was solved correctly.
- [ ] All changes were documented in CHANGELOG.md.
- [ ] All tests on CircleCI have passed.
- [ ] All Percy visual changes have been approved.
- [ ] Two people have :dancer:'d the pull request. You can be one of these people if you are a Dash core contributor.

### CODE REVIEW

**Comment by jourdain** [comment]
@xhlulu I'm not sure what is required next to bump the version and publish a new version? Can you take over that PR? Or let me know what I should do next. Thx

**Comment by xhlulu** [comment]
@jourdain Yeah I can handle releases. In fact it's probably better if I set it up to be automated; will think about that later.

I have a minor change to propose. Ok if I push directly to this branch?

**Comment by jourdain** [comment]
Yes go for it...

**Review by xhlulu — APPROVED** [review]
💃

**Pull request merged**
