### PR TITLE
Add Volume demos

### PR DESCRIPTION
**Pull request by xhlulu**
## Pre-Merge checklist
- [ ] The project was correctly built with `npm run build`.
- [ ] If there was any conflict, it was solved correctly.
- [ ] All changes were documented in CHANGELOG.md.
- [ ] All tests on CircleCI have passed.
- [ ] All Percy visual changes have been approved.
- [ ] Two people have :dancer:'d the pull request. You can be one of these people if you are a Dash core contributor.

## Reference Issues

Closes #[issue number]

## Other comments

### CODE REVIEW

**Comment by xhlulu** [comment]
Currently trying to add one for the Synthetic volume rendering demo, but getting this error when used in Dash: 
image

Here's my code:
```python
import random

import dash
import dash_vtk
import dash_html_components as html

data_url = "https://data.kitware.com/api/v1/item/59e12e988d777f31ac6455c5/download"

app = dash.Dash(__name__)
server = app.server

app.layout = html.Div(
    style={"height": "calc(100vh - 30px)", "width": "100%",},
    children=[
        dash_vtk.View(
            children=dash_vtk.VolumeDataRepresentation(
                spacing=[1,1,1],
                dimensions=[10,10,10],
                origin=[0,0,0],
                scalars=[random.random() for _ in range(1000)],
                rescaleColorMap=False
            )
        )
    ],
)

if __name__ == "__main__":
    app.run_server(debug=True)

```

**Comment by xhlulu** [comment]
@jourdain Any thoughts on that?

**Comment by jourdain** [comment]
Hum, not sure but I can look into it. Feel free to merge to master in the meantime while assigning an issue to me pointing on the code that does not work.

**Comment by xhlulu** [comment]
Ok I'm working on the slice rendering example, once that one is done i'll merge to master

**Pull request merged**
