### PR TITLE
Refactor component library structure in preparation for pypi release

### PR DESCRIPTION
**Pull request by xhlulu**
See commits for more details

### CODE REVIEW

**Comment by xhlulu** [comment]
@jourdain I've overwritten the commits such that each commit is cleanly separate from each other; I also added details below each commit. Though they should be self-explanatory, if there's something unclear please let me know!

**Review by jourdain — APPROVED** [review]
LGTM

**Comment by xhlulu** [comment]
@jourdain How do I modify the size of the cone? I know i have to modify the `state` prop but not sure what I need to change exactly.

**Comment by jourdain** [comment]
```
state={{
   height: 1,
   radius: 0.5,
   resolution: 60,
   direction: [1, 0, 0],
}}
```

**Comment by xhlulu** [comment]
Nice! Actually I just moved the app to `demos/usage-algorithm/app.py` and added a bunch of useful files. I also added a switch that lets you control the capping as well. Here's the end result:

demo

All in 70 lines of Python. I also used [dash bootstrap components](https://dash-bootstrap-components.opensource.faculty.ai/docs/) which is a third party library that integrates react-bootstrap into dash. Feel free to check out the library!

**Comment by xhlulu** [comment]
In my last three commits I added tests and circleCI automation. Merging now

**Pull request merged**
